// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/storagepb/stored_message.proto

// Package storagepb defines the internal Pebble value format for stored messages.
// This proto is NOT part of the public client API — it is only used between the
// broker's write path and the dispatcher/state machine.

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoredMessage is the value written to Pebble for each queued message.
// The corresponding key is a 24-byte composite: bucket | topic_hash | event_id.
type StoredMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// topic is the full topic name (kept in the value for populating consumer
	// QueueMessage.topic without a separate lookup).
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// payload is the opaque application data.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// enqueued_at_unix_ms is the broker wall-clock time (Unix ms) when the
	// message was first received. Used for TTL checks and consumer metadata.
	EnqueuedAtUnixMs int64 `protobuf:"varint,3,opt,name=enqueued_at_unix_ms,json=enqueuedAtUnixMs,proto3" json:"enqueued_at_unix_ms,omitempty"`
	// delay_ms is the original delay requested by the producer. Combined with
	// enqueued_at_unix_ms to compute fire_at = enqueued_at + delay_ms.
	DelayMs int64 `protobuf:"varint,4,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	// ttl_ms is the message time-to-live in milliseconds from enqueued_at.
	// 0 means no expiry.
	TtlMs         int64 `protobuf:"varint,5,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredMessage) Reset() {
	*x = StoredMessage{}
	mi := &file_internal_storagepb_stored_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredMessage) ProtoMessage() {}

func (x *StoredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storagepb_stored_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredMessage.ProtoReflect.Descriptor instead.
func (*StoredMessage) Descriptor() ([]byte, []int) {
	return file_internal_storagepb_stored_message_proto_rawDescGZIP(), []int{0}
}

func (x *StoredMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *StoredMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StoredMessage) GetEnqueuedAtUnixMs() int64 {
	if x != nil {
		return x.EnqueuedAtUnixMs
	}
	return 0
}

func (x *StoredMessage) GetDelayMs() int64 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *StoredMessage) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

var File_internal_storagepb_stored_message_proto protoreflect.FileDescriptor

const file_internal_storagepb_stored_message_proto_rawDesc = "" +
	"\n" +
	"'internal/storagepb/stored_message.proto\x12\tstoragepb\"\xa0\x01\n" +
	"\rStoredMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12-\n" +
	"\x13enqueued_at_unix_ms\x18\x03 \x01(\x03R\x10enqueuedAtUnixMs\x12\x19\n" +
	"\bdelay_ms\x18\x04 \x01(\x03R\adelayMs\x12\x15\n" +
	"\x06ttl_ms\x18\x05 \x01(\x03R\x05ttlMsB2Z0github.com/futureq-io/futureq/internal/storagepbb\x06proto3"

var (
	file_internal_storagepb_stored_message_proto_rawDescOnce sync.Once
	file_internal_storagepb_stored_message_proto_rawDescData []byte
)

func file_internal_storagepb_stored_message_proto_rawDescGZIP() []byte {
	file_internal_storagepb_stored_message_proto_rawDescOnce.Do(func() {
		file_internal_storagepb_stored_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_storagepb_stored_message_proto_rawDesc), len(file_internal_storagepb_stored_message_proto_rawDesc)))
	})
	return file_internal_storagepb_stored_message_proto_rawDescData
}

var file_internal_storagepb_stored_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_storagepb_stored_message_proto_goTypes = []any{
	(*StoredMessage)(nil), // 0: storagepb.StoredMessage
}
var file_internal_storagepb_stored_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_storagepb_stored_message_proto_init() }
func file_internal_storagepb_stored_message_proto_init() {
	if File_internal_storagepb_stored_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_storagepb_stored_message_proto_rawDesc), len(file_internal_storagepb_stored_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_storagepb_stored_message_proto_goTypes,
		DependencyIndexes: file_internal_storagepb_stored_message_proto_depIdxs,
		MessageInfos:      file_internal_storagepb_stored_message_proto_msgTypes,
	}.Build()
	File_internal_storagepb_stored_message_proto = out.File
	file_internal_storagepb_stored_message_proto_goTypes = nil
	file_internal_storagepb_stored_message_proto_depIdxs = nil
}
