// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: consumer.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FutureQConsumer_Subscribe_FullMethodName = "/futureq.FutureQConsumer/Subscribe"
)

// FutureQConsumerClient is the client API for FutureQConsumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FutureQConsumerClient interface {
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AckRequest, QueueMessage], error)
}

type futureQConsumerClient struct {
	cc grpc.ClientConnInterface
}

func NewFutureQConsumerClient(cc grpc.ClientConnInterface) FutureQConsumerClient {
	return &futureQConsumerClient{cc}
}

func (c *futureQConsumerClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AckRequest, QueueMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FutureQConsumer_ServiceDesc.Streams[0], FutureQConsumer_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AckRequest, QueueMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FutureQConsumer_SubscribeClient = grpc.BidiStreamingClient[AckRequest, QueueMessage]

// FutureQConsumerServer is the server API for FutureQConsumer service.
// All implementations must embed UnimplementedFutureQConsumerServer
// for forward compatibility.
type FutureQConsumerServer interface {
	Subscribe(grpc.BidiStreamingServer[AckRequest, QueueMessage]) error
	mustEmbedUnimplementedFutureQConsumerServer()
}

// UnimplementedFutureQConsumerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFutureQConsumerServer struct{}

func (UnimplementedFutureQConsumerServer) Subscribe(grpc.BidiStreamingServer[AckRequest, QueueMessage]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedFutureQConsumerServer) mustEmbedUnimplementedFutureQConsumerServer() {}
func (UnimplementedFutureQConsumerServer) testEmbeddedByValue()                         {}

// UnsafeFutureQConsumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FutureQConsumerServer will
// result in compilation errors.
type UnsafeFutureQConsumerServer interface {
	mustEmbedUnimplementedFutureQConsumerServer()
}

func RegisterFutureQConsumerServer(s grpc.ServiceRegistrar, srv FutureQConsumerServer) {
	// If the following call panics, it indicates UnimplementedFutureQConsumerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FutureQConsumer_ServiceDesc, srv)
}

func _FutureQConsumer_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FutureQConsumerServer).Subscribe(&grpc.GenericServerStream[AckRequest, QueueMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FutureQConsumer_SubscribeServer = grpc.BidiStreamingServer[AckRequest, QueueMessage]

// FutureQConsumer_ServiceDesc is the grpc.ServiceDesc for FutureQConsumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FutureQConsumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "futureq.FutureQConsumer",
	HandlerType: (*FutureQConsumerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _FutureQConsumer_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "consumer.proto",
}
