// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: producer.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FutureQProducer_PublishStream_FullMethodName = "/futureq.FutureQProducer/PublishStream"
)

// FutureQProducerClient is the client API for FutureQProducer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FutureQProducerClient interface {
	PublishStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamPublishRequest, StreamPublishAck], error)
}

type futureQProducerClient struct {
	cc grpc.ClientConnInterface
}

func NewFutureQProducerClient(cc grpc.ClientConnInterface) FutureQProducerClient {
	return &futureQProducerClient{cc}
}

func (c *futureQProducerClient) PublishStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamPublishRequest, StreamPublishAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FutureQProducer_ServiceDesc.Streams[0], FutureQProducer_PublishStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPublishRequest, StreamPublishAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FutureQProducer_PublishStreamClient = grpc.BidiStreamingClient[StreamPublishRequest, StreamPublishAck]

// FutureQProducerServer is the server API for FutureQProducer service.
// All implementations must embed UnimplementedFutureQProducerServer
// for forward compatibility.
type FutureQProducerServer interface {
	PublishStream(grpc.BidiStreamingServer[StreamPublishRequest, StreamPublishAck]) error
	mustEmbedUnimplementedFutureQProducerServer()
}

// UnimplementedFutureQProducerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFutureQProducerServer struct{}

func (UnimplementedFutureQProducerServer) PublishStream(grpc.BidiStreamingServer[StreamPublishRequest, StreamPublishAck]) error {
	return status.Error(codes.Unimplemented, "method PublishStream not implemented")
}
func (UnimplementedFutureQProducerServer) mustEmbedUnimplementedFutureQProducerServer() {}
func (UnimplementedFutureQProducerServer) testEmbeddedByValue()                         {}

// UnsafeFutureQProducerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FutureQProducerServer will
// result in compilation errors.
type UnsafeFutureQProducerServer interface {
	mustEmbedUnimplementedFutureQProducerServer()
}

func RegisterFutureQProducerServer(s grpc.ServiceRegistrar, srv FutureQProducerServer) {
	// If the following call panics, it indicates UnimplementedFutureQProducerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FutureQProducer_ServiceDesc, srv)
}

func _FutureQProducer_PublishStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FutureQProducerServer).PublishStream(&grpc.GenericServerStream[StreamPublishRequest, StreamPublishAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FutureQProducer_PublishStreamServer = grpc.BidiStreamingServer[StreamPublishRequest, StreamPublishAck]

// FutureQProducer_ServiceDesc is the grpc.ServiceDesc for FutureQProducer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FutureQProducer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "futureq.FutureQProducer",
	HandlerType: (*FutureQProducerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishStream",
			Handler:       _FutureQProducer_PublishStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "producer.proto",
}
