// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: producer.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamPublishRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Topic           string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload         []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ExecuteAtUnixMs int64                  `protobuf:"varint,4,opt,name=execute_at_unix_ms,json=executeAtUnixMs,proto3" json:"execute_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamPublishRequest) Reset() {
	*x = StreamPublishRequest{}
	mi := &file_producer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPublishRequest) ProtoMessage() {}

func (x *StreamPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_producer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPublishRequest.ProtoReflect.Descriptor instead.
func (*StreamPublishRequest) Descriptor() ([]byte, []int) {
	return file_producer_proto_rawDescGZIP(), []int{0}
}

func (x *StreamPublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *StreamPublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamPublishRequest) GetExecuteAtUnixMs() int64 {
	if x != nil {
		return x.ExecuteAtUnixMs
	}
	return 0
}

type StreamPublishAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPublishAck) Reset() {
	*x = StreamPublishAck{}
	mi := &file_producer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPublishAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPublishAck) ProtoMessage() {}

func (x *StreamPublishAck) ProtoReflect() protoreflect.Message {
	mi := &file_producer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPublishAck.ProtoReflect.Descriptor instead.
func (*StreamPublishAck) Descriptor() ([]byte, []int) {
	return file_producer_proto_rawDescGZIP(), []int{1}
}

func (x *StreamPublishAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamPublishAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_producer_proto protoreflect.FileDescriptor

const file_producer_proto_rawDesc = "" +
	"\n" +
	"\x0eproducer.proto\x12\afutureq\"s\n" +
	"\x14StreamPublishRequest\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12+\n" +
	"\x12execute_at_unix_ms\x18\x04 \x01(\x03R\x0fexecuteAtUnixMs\"Q\n" +
	"\x10StreamPublishAck\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2`\n" +
	"\x0fFutureQProducer\x12M\n" +
	"\rPublishStream\x12\x1d.futureq.StreamPublishRequest\x1a\x19.futureq.StreamPublishAck(\x010\x01B(Z&github.com/futureq-io/futureq/proto/gob\x06proto3"

var (
	file_producer_proto_rawDescOnce sync.Once
	file_producer_proto_rawDescData []byte
)

func file_producer_proto_rawDescGZIP() []byte {
	file_producer_proto_rawDescOnce.Do(func() {
		file_producer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_producer_proto_rawDesc), len(file_producer_proto_rawDesc)))
	})
	return file_producer_proto_rawDescData
}

var file_producer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_producer_proto_goTypes = []any{
	(*StreamPublishRequest)(nil), // 0: futureq.StreamPublishRequest
	(*StreamPublishAck)(nil),     // 1: futureq.StreamPublishAck
}
var file_producer_proto_depIdxs = []int32{
	0, // 0: futureq.FutureQProducer.PublishStream:input_type -> futureq.StreamPublishRequest
	1, // 1: futureq.FutureQProducer.PublishStream:output_type -> futureq.StreamPublishAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_producer_proto_init() }
func file_producer_proto_init() {
	if File_producer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_producer_proto_rawDesc), len(file_producer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_producer_proto_goTypes,
		DependencyIndexes: file_producer_proto_depIdxs,
		MessageInfos:      file_producer_proto_msgTypes,
	}.Build()
	File_producer_proto = out.File
	file_producer_proto_goTypes = nil
	file_producer_proto_depIdxs = nil
}
